---
title: "Football match prediction using Correlated features and the bivariate Poisson Distribution."
author: "Suhishan Bhandari"
date: "December 25, 2025"
format:
  html: 
    code-fold: true
    code-tools: true
toc: TRUE
execute:
  message: false
  warning: false
---

```{r}
#| label: load packages
#| include: false
packages <- c("tidyverse","cmdstanr","bayesplot","loo","posterior","qs", "patchwork")
lapply(packages, library, character.only = TRUE)

```


```{r}
#| include: false
#| label : data cleaning and stuff

data <-  read.csv("data/premfull23_24.csv")

data = data %>% select(HomeTeam, HomeGoals, AwayGoals, AwayTeam) %>% 
  rename(
    Home = HomeTeam,
    s1 = HomeGoals,
    s2 = AwayGoals,
    Away = AwayTeam
  )

# Recode team names.
lookup <- c(
     "Brighton and Hove Albion" = "Brighton",
     "Manchester Utd" = "Manchester United",
     "Newcastle Utd" = "Newcastle United",
     "Nott'ham Forest" = "Nottingham Forest",
     "Sheffield Utd" = "Sheffield United",
     "Tottenham Hotspur" = "Tottenham",
     "West Ham United" = "West Ham",
     "Wolverhampton Wanderers" = "Wolves"
)

data = data %>% mutate(
  Home = recode(Home, !!!lookup),
  Away = recode(Away, !!!lookup)
)


teams = unique(data$Home) # Team names
ng = nrow(data) # number of games
nt = length(unique(data$Home)) # number of teams
# Home team index
ht = unlist(sapply(1:ng, function(g) which(teams == data$Home[g]))) 
# Away team index
at = unlist(sapply(1:ng, function(g) which(teams == data$Away[g]))) 
np = 10 # Number of games to be predicted i.e. test sample length
ngd = ng - np # Number of games used to train i.e. train sample length.

```


```{r}
#| include: false
score_matrix <- function(post, game){
  n_sample <- length(post[[game]])
  home_p <- table(post[[game]])/n_sample # Posterior proportions of scores
  away_p <- table(post[[game + 10]])/n_sample
  
  # Matrix of results.
  m = round(home_p %o% away_p, 3)
  return (m)
}

# Win/Loss/Draw Percentages.

result_prob <- function(post, game) {
  m = score_matrix(post, game)
  hw = sum(m[lower.tri(m)])
  d = sum(diag(m))
  aw = sum(m[upper.tri(m)])
  
  return(c(hw = hw, d = d, aw = aw))
}

```



